version: '3'

services:
  nginx:
    container_name: ${PROJECT_NAME}_nginx
    build: ./src/nginx
    volumes:
      - ./logs/nginx/:${NGINX_LOG_DIR}
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    networks:
      fourb_net:
        ipv4_address: ${NGINX_IP}
    environment:
      - NGINX_HOST=${NGINX_IP}
      - NGINX_PORT=${NGINX_PORT}

  db:
    container_name: ${PROJECT_NAME}_db
    build:
      context: ./src/database
      args:
        - DB_CONTAINER_USER=${DB_CONTAINER_USER}
        - DB_CONTAINER_GROUP=${DB_CONTAINER_GROUP}
    command:
      --default-authentication-plugin=mysql_native_password
    volumes:
      - ./logs/db:${DB_LOG_DIR}
      - ./data:${DB_DATA_DIR}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      fourb_net:
        ipv4_address: ${DB_IP}
    environment:
      - MYSQL_CONTAINER_USER=${DB_CONTAINER_USER}
      - MYSQL_CONTAINER_GROUP=${DB_CONTAINER_GROUP}
      - MYSQL_ROOT_USER=${DB_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DB_NAME=${DB_NAME}

  frontend:
    container_name: ${PROJECT_NAME}_frontend
    build:
      context: ./src/frontend
      args:
        - FRONTEND_WORKDIR=${FRONTEND_WORKDIR}
    restart: always
    volumes:
      - ./src/frontend:${FRONTEND_WORKDIR}
      - ${FRONTEND_WORKDIR}/node_modules
    ports:
      - 3000:3000
    networks:
      fourb_net:
        ipv4_address: ${FRONTEND_IP}

  backend:
    container_name: ${PROJECT_NAME}_backend
    build:
      context: ./src/backend
      args:
        - BACKEND_WORKDIR=${BACKEND_WORKDIR}
    restart: always
    volumes:
      - ./src/backend:${BACKEND_WORKDIR}
      - ./static:${BACKEND_STATIC_FILES}
    ports:
      - 8081:8081
    networks:
      fourb_net:
        ipv4_address: ${BACKEND_IP}
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - DB_HOST=${DB_IP}
      - DB_USER=${DB_ROOT_USER}
      - DB_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_NAME=${DB_NAME}
      - BACKEND_WORKDIR=${BACKEND_WORKDIR}
      - BACKEND_STATIC_FILES=${BACKEND_STATIC_FILES}
      - BACKEND_UPLOAD_LIMIT=${BACKEND_UPLOAD_LIMIT}

networks:
  fourb_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}
